services:
  - type: web
    name: procontrol
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PUBLIC_BASE_URL
        sync: false
      - key: DATABASE_URL
        sync: false
